contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
    
    # contact (CRUD)
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    # path('contact/<int:contact_id>/delete/', views.contact, name='contact'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.name}'


class Contact(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Nome')
    last_name = models.CharField(max_length=50, verbose_name='Sobrenome')
    phone = models.CharField(max_length=50, verbose_name='Telefone')
    email = models.EmailField(max_length=254, blank=True, verbose_name='E-mail')
    description = models.TextField(blank=True, verbose_name='Descrição')
    created_date = models.DateTimeField(default=timezone.now, verbose_name='Data de criação')
    show = models.BooleanField(default=True, verbose_name='Mostrar') 
    pictures = models.ImageField(blank=True, upload_to='pictures/%Y/%m/', verbose_name='Fotos')
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        blank=True, null=True
        , verbose_name='Categoria')
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='Usuário'
    )
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django.core.exceptions import ValidationError
from django import forms

from . import models

class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'classe-a classe-b',
                'placeholder' : 'Escreva aqui'
            }
        ),
        label='Nome', 
        help_text='Texto de ajuda para seu usuário'
    )

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    #     self.fields['first_name'].widget.attrs.update({
    #         'class' : 'classe-a classe-b',
    #         'placeholder' : 'Escreva aqui'
    #     })

    class Meta:
        model = models.Contact
        fields = (
            'first_name', 'last_name', 'phone',          
            'email', 'description', 'category',          
        )
        # widgets = {
        #     'first_name': forms.TextInput(
        #         attrs={
        #             'class' : 'classe-a classe-b',
        #             'placeholder' : 'Escreva aqui'
        #         }
        #     )
        # }

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo', 
                code='invalid')
            self.add_error('first_name', msg)
            self.add_error('last_name', msg)
        
        if len(last_name) < 3:
            msg = ValidationError(
                'Campo sobrenome deve ter no mínimo 3 caracteres', 
                code='invalid')
            self.add_error('last_name', msg)
        return super().clean()


    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if len(first_name) < 3:
            raise ValidationError(
                'Campo nome deve ter no mínimo 3 caracteres'
                )
        
        return first_name

contact/views.py
from django.shortcuts import render

def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from contact.forms import ContactForm
from contact.models import Contact

def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }
        
        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        
        return render(
            request, 
            'contact/create.html', 
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action
    }
    return render(request, 'contact/create.html', context)

def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    form_action = reverse('contact:update', args=(contact_id,))
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        
        context = {
            'form': form,
            'form_action': form_action
        }
        
        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        
        return render(
            request, 
            'contact/create.html', 
            context
        )

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action
    }
    return render(request, 'contact/create.html', context)

contact/views/contact_views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render 
from django.db.models import Q
from contact.models import Contact
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects\
        .filter(show=True)\
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    print(contacts.query)
    context = {
        'page_obj': page_obj,
    }
    return render(
        request,
        'contact/index.html',
        context
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')
    
    contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
            )\
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Pesquisa - ',
        'search_value' : search_value
    }

    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(
        Contact, pk=contact_id, show=True
        )
    
    site_title = f'{single_contact.first_name} {single_contact.last_name} - '

    context = {
        'contact': single_contact,
        'site_title' : site_title
    }
    return render(
        request,
        'contact/contact.html',
        context
    )

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>
        <p class=""><b>ID: </b>{{ contact.id }}</p>
        <p class=""><b>E-mail: </b>{{ contact.email }}</p>
        <p class=""><b>Telefone: </b>{{ contact.phone }}</p>
        <p class=""><b>Data de criação: </b>{{ contact.created_date }}</p>
        <p class=""><b>Descrição: </b>{{ contact.description }}</p>
        <p class=""><b>Categoria: </b>{{ contact.category.name }}</p>
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <h2>Contact</h2>

        <form action=" {{ form_action }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

           <div class="form-content">
                {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}

                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">                            
                            {{ form.non_field_errors }}                                              
                        </div>     
                    </div>  
                </div>
            {% endif %}

            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Salvar</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
    {% if page_obj %} 
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">Contatos</caption>
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">Nome</th>
                        <th class="table-header">Sobrenome</th>
                        <th class="table-header">Telefone</th>
                        <th class="table-header">E-mail</th>
                    </tr>
                </thead>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" 
                            href=" {% url "contact:contact" contact.id %}">
                                {{ contact.id }}
                            </a>                
                        </td>
                        <td class="table-cel">                
                                {{ contact.first_name }} 
                        </td>
                        <td class="table-cel">                
                                {{ contact.last_name }} 
                        </td>
                        <td class="table-cel">                
                                {{ contact.phone }} 
                        </td>
                        <td class="table-cel">                
                                {{ contact.email }} 
                        </td>
                    </tr>
                {% endfor %}
            </table>

        </div>
    {% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum contato encontrado.
        </h1>
    </div>
    {% endif %}
{% endblock content %}